environment:
  - wake_word=コンピュータ # ウェイクワード
  - mic_samplerate=16000 # マイクの入力サンプリングレート。マイクのコーデックがmSbcの場合は16000、CVSDの場合は8000。
  - vosk_model_path=/home/tane/datas/voice/vosk-model-ja-0.22 # VOSKのモデルファイルを置いているパス
  - silence_duration=3.5 # 質問の終了を検知するまでの無音時間（秒）。
  - llm_URL=http://127.0.0.1:5005 # tane_chat（LLMサーバ）のURL
  - llm_system_prompt=あなたは日本人です。どんな簡単な単語でも、全て日本語で回答して下さい。５０文字以内に要約して回答してください。 # LLMの system prompt
  - llm_max_tokens=256 # LLMの出力の最大トークン数
  - voicevox_URL=http://127.0.0.1:50021 # voicevox-engineのURL
  - voicevox_speaker_id=3 # voicevox-engineのスピーカーID。3はずんだもん。
  - voicevox_speedScale=1.0 # 返答の発声速度
  - voicevox_prePhonemeLength=0.6 # 発声の前の無音時間
  - voicevox_outputSamplingRate=16000 # 音声の出力サンプリングレート
