services:
  tanexa:
    image: tanep/tanexa:latest
    environment:
      - TANEXA_WAKE_WORD=コンピュータ          # ウェイクワード
      - TANEXA_MIC_SAMPLE_RATE=16000          # マイクの入力サンプリングレート。マイクのコーデックがmSbcの場合は16000、CVSDの場合は8000。
      - TANEXA_SILENCE_DURATION=3.5           # 質問の終了を検知するまでの無音時間（秒）。
      - TANEXA_LLM_URL=http://127.0.0.1:5005  # tane_chat（LLMサーバ）のURL
      - TANEXA_LLM_SYSTEM_PROMPT=あなたは日本人です。どんな簡単な単語でも、全て日本語で回答して下さい。５０文字以内に要約して回答してください。  # LLMの system prompt
      - TANEXA_LLM_MAX_TOKENS=256             # LLMの出力の最大トークン数
      - TANEXA_VOICEVOX_URL=http://127.0.0.1:50021  # voicevox-engineのURL
      - TANEXA_VOICEVOX_SPEAKER_ID=3          # voicevox-engineのスピーカーID。3はずんだもん。
      - TANEXA_VOICEVOX_SPEED_SCALE=1.0       # 返答の発声速度
      - TANEXA_VOICEVOX_PREPHONEME_LENGTH=0.6 # 発声の前の無音時間
      - TANEXA_VOICEVOX_OUTPUT_SAMPLING_RATE=16000  # 音声の出力サンプリングレート
    volumes:
      - /VOSKのモデルファイルを置いているパス:/app/vosk_model  # モデルファイルをコンテナにマウント
      - /run/user/1000/pulse:/run/user/1000/pulse   # PulseAudioソケットをマウント
      - $XDG_RUNTIME_DIR/pulse/native:/run/pulse/native   # PulseAudioのランタイムソケットをマウント
    environment:
      - PULSE_SERVER=unix:/run/pulse/native   # Linuxの場合
    #  - PULSE_SERVER=tcp:localhost           # Mac、Windowsの場合
    # サウンドデバイスサポートの追加
    devices:
      - /dev/snd:/dev/snd  # ホストのサウンドデバイスをコンテナに渡す
    privileged: true        # コンテナがサウンドデバイスにアクセスできるようにする
    tty: true  # ターミナルのインタラクションを有効にするための設定（必要に応じて）
